clc, clear all, close all;
%% Import data from text file
% Script for importing data from the following text file:
% filename: C:\Users\BKhan\OneDrive - Mynaric AG\Documents\Python Scripts\state_history.dat
% Auto-generated by MATLAB on 14-Nov-2022 09:16:59
% Generic approach. Can shift Past/Future

%% Set up the Import Options and import the datae

opts = delimitedTextImportOptions("NumVariables", 25);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
statehistory = readtable("C:\Users\BKhan\OneDrive - Mynaric AG\Documents\Python Scripts\state_history.dat", opts);

% Clear temporary variables
clear opts

%% Initial values of r and v for HOST and TARGET
format long;
%----original
%LEO_HOST_r = table2array(statehistory(:,(2:4)))*1e-3; % [km]
%LEO_HOST_v = table2array(statehistory(:,(5:7)))*1e-3; % [km/s]

%LEO_INPLANE_TARGET_r = table2array(statehistory(:,(8:10)))*1e-3; % [km]
%LEO_INPLANE_TARGET_v = table2array(statehistory(:,(11:13)))*1e-3; % [km/s]
%----------
LEO_HOST_r = (table2array(statehistory(:,(8:10)))*1e-3); % [km]
LEO_HOST_v = (table2array(statehistory(:,(11:13)))*1e-3); % [km/s]

LEO_INPLANE_TARGET_r = (table2array(statehistory(:,(2:4)))*1e-3); % [km]
LEO_INPLANE_TARGET_v = (table2array(statehistory(:,(5:7)))*1e-3); % [km/s]


LEO_CROSS_TARGET_r = (table2array(statehistory(:,(14:16)))*1e-3); % [km]
LEO_CROSS_TARGET_v = (table2array(statehistory(:,(17:19)))*1e-3); % [km/s]

time = (table2array(statehistory(:,1))-table2array(statehistory(1,1)));

% Select TARGET trajectory to Porpagate :
% r = LEO_INPLANE_TARGET_r;
% v = LEO_INPLANE_TARGET_v;
% t_title = "LEO-INPLANE-TARGET";

r = LEO_CROSS_TARGET_r;
v = LEO_CROSS_TARGET_v;
t_title = "LEO-CROSSPLANE-TARGET";

figure(1);
for i=1:length(LEO_HOST_r(:,1))
    delta_r(i)   = norm(LEO_HOST_r(i,:) - LEO_CROSS_TARGET_r(i,:));
    delta_r_2(i) = norm(LEO_INPLANE_TARGET_r(i,:) - LEO_CROSS_TARGET_r(i,:));
end
plot(table2array(statehistory(:,1)),delta_r);
hold on;
plot(table2array(statehistory(:,1)),delta_r_2, 'r');
grid on;

% CONSTANTS
global mu J2 R
mu = 398600.44; %km^3/s^2
J2 = 1082.6267 * 10^-6;
R = 6378.1366; %km  Earth Radius
%% SIMULATION PARAMETERS
% 
%path1 = zeros(length(r), 6);
options = odeset('abstol',1e-12,'reltol',1e-12); % set tolerances


% Starting position definition
% disp("Simulate from the TARGET position @ 0th second, which is 'start_point'seceonds in the past. 
% Starting the sim. at HOST position @ jth sec.MATLAB indexing starts with 1 but time @ t_0 = 0");

% %% Shift HOST initial zero Pos. r(1,:) to "start_point"

if (abs(LEO_HOST_r-LEO_CROSS_TARGET_r) < 300 )
    aa = abs(LEO_HOST_r-LEO_CROSS_TARGET_r)
end

%start_point = 2801; % 2801 for ~500km range
start_point = 2587; % 2400 for ~250km range
%start_point = 1801; % 1801 for ~2000km tange 

% LEO_HOST_r = LEO_HOST_r(start_point:end,:);
% LEO_HOST_v = LEO_HOST_v(start_point:end,:);

% Downsample
step = 1;
% LEO_HOST_r = downsample(LEO_HOST_r,step);
% LEO_HOST_v = downsample(LEO_HOST_v,step);

display("############----PROPAGATION SIMULATION----#############");
fprintf("Shifting HOST initial zero position to: %d sec\n", start_point);
display('So for simulation this will be HOST initial position.');
q1 = "\nTARGET intial ephemeris delay in sec [max. 50]?: [If no delay, put 0] :";
target_delay = (start_point - input(q1));   % say 30 [sec]

%% %%%%%%%---TARGET---%%%%%%%%%%%%%%% 
r_target = r;%(target_delay:end,:);
v_target = v;%(target_delay:end,:);
t_init = target_delay;
% r_target = downsample(r_target,step);
% v_target = downsample(v_target,step);

v_sv_op = [r_target(1,:), v_target(1,:)];  

%%  % Interpolated data for HOST-TARGET

q3 = "\nHow many ephemeris update will receive? :";
update_no = input(q3);

% Duration of propagation [sec]
prop_duration = (10);
prop_timeout = start_point+100;
fprintf("SDA limiting propagation timeout (considering HOST position shift by %d: %d sec", start_point, prop_timeout);
prop_end = prop_duration;

state = [];
LOS_true = [];
LOS_prop = [];
LOS_prop_single = ([]);
t1 = [];
pos_init = start_point;
i = 1;
temp = [];
start_point_array = [];
%for (i=1:1:update_no)
new_data = t_init + [10,20,30];%sort(t_init + randi(100,1,update_no));%sort(start_point + randperm(update_no));
%end
    while (prop_end <= prop_timeout)        
        %fprintf("\nSend an Update of TARGET ephemeris after %d [sec]", new_data(i)-start_point);   
        if  ~(i > update_no) && (new_data(i) <= start_point + prop_duration)   %
            prop_end = new_data(i);
            update = true;
            fprintf('\nNew data will arrive at:%d, so propagating upto :%d [sec]',prop_end,prop_end-1);
        else
            prop_end = start_point + prop_duration-1;
            update = false;
            fprintf('\nNo New data arrived within %d sec, so Propagating upto :%d [sec]',prop_duration, prop_end);
        end

    % Propagation from the 1st TARGET data
    % Find the timestamp of TARGET data  
    fprintf('\nt_init: %d\n',t_init);
    tspan = (time(t_init:step:prop_end,1));
    tspan_single = single(time(t_init:step:prop_end,1));
    temp = vertcat(temp,t_init); % check the initial values loaded perfectly
    
    if (update)|| (i<2)
        v_sv_op = [r_target(t_init,:), v_target(t_init,:)];
        v_sv_op_single = single([r_target(t_init,:), v_target(t_init,:)]);
    else
        v_sv_op = [r_prop_1(end,:), v_prop_1(end,:)];
        v_sv_op_single = single([r_prop_1(end,:), v_prop_1(end,:)]);
        fprintf("%f, %d", v_sv_op(1), t_init);
    end

    % Integration timespan
    [t,path1] = odeRK(@orbit_prop,tspan, v_sv_op');
    [t_single,path1_single] = odeRK_single(@orbit_prop,tspan_single, v_sv_op_single');
    fprintf('\n%d Propagating from %d to %d\n',i,tspan(1),tspan(end)); 
    
    r_prop_1 = (path1(:,1:3));
    r_prop_1_single = (path1_single(:,1:3));
    v_prop_1 = (path1(:,4:6));
    
    LOS_true = vertcat(LOS_true, abs(LEO_HOST_r(start_point:start_point+length(t)-1,:)- r_target(t_init:t_init+length(t)-1,:)));
    LOS_prop_single = vertcat(LOS_prop_single, (abs((LEO_HOST_r(start_point:start_point+length(t)-1,:))- r_prop_1_single)));
    LOS_prop = vertcat(LOS_prop, (abs((LEO_HOST_r(start_point:start_point+length(t)-1,:))- r_prop_1)));
    t1 = vertcat(t1,t);
  
    aa = LEO_HOST_r(start_point:step:start_point+length(t)-1,:);%LEO_HOST_r(start_point:end,:);%
    bb = r_target(t_init:step:t_init+length(t)-1,:);%r_target(t_init:end,:);
    cc = r_prop_1;
    
    % reload variables 
    i = i+1;
    t_init = prop_end;
    prop_end = t_init + prop_duration;
    if prop_end > prop_timeout
        break;
    end
    start_point = prop_end;
    end 

for ii=1:length((t1))
    theta(ii) = 1e6*acos(dot(double(LOS_prop_single(ii,:)), LOS_true(ii,:))/(norm(double(LOS_prop_single(ii,:)))*norm(LOS_true(ii,:))));

end
for i=1:length((t1))

     theta_double(i) = 1e6*acos(dot(LOS_prop(i,:), LOS_true(i,:))/(norm(LOS_prop(i,:))*norm(LOS_true(i,:))));
end


%%  ---------------------- TEST-----------------------------------------

ddot = zeros(size(LOS_true(:,1)));

for i = 1:length(LOS_true(:,1))
    ddot(i) = (dot(LOS_true(i,:), double(LOS_prop_single(i,:))));
%     ddot_db(i) = (dot(LOS_true(i,:), LOS_prop(i,:)));
    nn(i) = norm(LOS_true(i,:))*norm(double(LOS_prop_single(i,:)));
%     nn(i) = sqrt(sum(LOS_true(i,:).^2)*sum(LOS_prop_single(i,:).^2));
    tthh(i) = 1e6*acos(ddot(i)/nn(i));

end
figure(12);
plot(t1-pos_init,tthh);
grid();

figure('color','white');
plot3(LEO_CROSS_TARGET_r(:,1),LEO_CROSS_TARGET_r(:,2),LEO_CROSS_TARGET_r(:,3),'DisplayName','LEO CROSS TARGET');
hold on;
plot3(LEO_INPLANE_TARGET_r(:,1),LEO_INPLANE_TARGET_r(:,2),LEO_INPLANE_TARGET_r(:,3),'DisplayName','LEO INPLANE TARGET');
plot3(LEO_HOST_r(start_point:end,1),LEO_HOST_r(start_point:end,2),LEO_HOST_r(start_point:end,3),'DisplayName','LEO HOST');
%hold on;
plot3(r(start_point:end,1),r(start_point:end,2),r(start_point:end,3),'Blue','DisplayName','rTarget');
plot3(aa(:,1),aa(:,2),aa(:,3),'-o','MarkerSize',10,...
    'MarkerFaceColor','Yellow','DisplayName','HosT');
plot3(bb(:,1),bb(:,2),bb(:,3),'-o','MarkerSize',10,...
    'MarkerFaceColor','#D9FFFF','DisplayName','Target');
%plot3(cc(:,1),cc(:,2),cc(:,3),'-bo');%,'MarkerSize',10,...
    %'MarkerFaceColor','Red','DisplayName','HosT');
xlabel('ECI x [m]');
ylabel('ECI y [m]');
zlabel('ECI z [m]');
title('Satellite Orbit in ECI Coordinates');
grid on
legend

%% ----------------------END TEST--------------------------------------

% if (prop_again)
%     for i=1:length(t3)
%         theta_start_point1(i) = 1e6*acos(dot(LOS_prop_start_point1(i,:), LOS_true_start_point1(i,:))/(norm(LOS_prop_start_point1(i,:))*norm(LOS_true_start_point1(i,:))));
%     end
% end

figure(3);

plot(t1-pos_init, theta,'r-o');
grid();
% figure(2)
hold on;
plot(t1-pos_init, theta_double, 'b-o');
% if(prop_again)
%     scatter(t3, theta_start_point1, 'g');
% end
ylabel('LOS Pointing Error [µrad]');
xlabel('Time [sec]');
title(sprintf('%s, and propagation duration: %d [sec]',t_title,prop_duration));
legend('Single Precision', 'Double Precision');
% figure(2)
% plot(t_ext_h,LEO_HOST_r, 'b.')
% alpha(0.2);
% hold on
% plot(t_orig,LEO_HOST_r,'r-o')
% figure(3)
% plot(t2-pos_init,state_ext(:,3),'cyan-o')
% hold on
% plot(t1-pos_init,state(:,3),'r*')
% figure(4);
% plot(t1-pos_init, LOS_prop, 'r*');
% hold on
% plot(t2-pos_init, LOS_prop_ext, 'cyan-o');
% grid()
function dydt = orbit_prop(t,vec_sv)    
    % CONSTANTS
    global mu J2 R
    mu = 398600.44; %km^3/s^2
    J2 = 1082.6267 * 10^-6;
    R = 6378.1366; %km  Earth Radius
    
    %INPUTS
    r0 = vec_sv(1:3);
    v0 = vec_sv(4:6);
    a1 = -(mu/(norm(r0)^3))*r0;
    
    %% J2 Perturbations:
    r_norm = norm(r0);
    
    const = -3 * J2 * mu * R^2/(2 * r_norm^5); 
    ai = const*(5*r0(3)^2/r_norm^2 -1);
    aj = const*(5*r0(3)^2/r_norm^2 -1);
    ak = const*(5*r0(3)^2/r_norm^2 -3);
    acc = [ai; aj; ak];
    a = a1 + acc ;

    dydt = [v0(1), v0(2), v0(3), a(1), a(2), a(3)]';
end

%% Runge-Kutta (RK4) Numerical Integration for System of Differential Equations
function [tspan,x] = odeRK(forbit,tspan,x0)
    % tspan = 1xN matrix of t values
    % x0 = nx1 matrix of initial conditions
    % returns t=tspan, x=nxN matrix
    % x(:,i) = x(t(i))
    N = length(tspan);
    n = length(x0);
    x0 = reshape(x0,n,1);
    x = [x0 zeros(n,N-1)];
    w = x0;
    for i = 1:N-1
        h = tspan(i+1)-tspan(i);
        t = tspan(i);
        K1 = h*forbit(t,w);
        K2 = h*forbit(t+h/2,w+K1/2);
        K3 = h*forbit(t+h/2,w+K2/2);
        K4 = h*forbit(t+h,w+K3);
        w = w+(K1+2*K2+2*K3+K4)/6;
        x(:,i+1) = w;
    end
    x = x';
end
function [tspan,x] = odeRK_single(forbit,tspan,x0)
    % tspan = 1xN matrix of t values
    % x0 = nx1 matrix of initial conditions
    % returns t=tspan, x=nxN matrix
    % x(:,i) = x(t(i))
    tspan = single(tspan);
    x0 = single(x0);
    N = length(tspan);
    n = length(x0);
    x0 = reshape(x0,n,1);
    x = [x0 zeros(n,N-1)];
    w = x0;
    for i = 1:N-1
        h = tspan(i+1)-tspan(i);
        t = tspan(i);
        K1 = h*forbit(t,w);
        K2 = h*forbit(t+h/2,w+K1/2);
        K3 = h*forbit(t+h/2,w+K2/2);
        K4 = h*forbit(t+h,w+K3);
        w = w+(K1+2*K2+2*K3+K4)/6;
        x(:,i+1) = w;
    end
    x = x';
end
function [X,Y] = interpolate (time, data)
    Y = [];
    X = [];
    for j = 1:length(time)-1
        x = [time(j), time(j+1)];   % time
        xq = linspace(time(j),time(j+1),200);  
        for jj=1:size(data,2)        
            y = [data(j,jj),data(j+1,jj)];     % data       
            yq(:,jj) = interp1(x,y,xq);          
        end
       Y = vertcat(Y,yq);
       X = vertcat(X,xq');
    end
end

